[package]
name = "renderer"
version = "0.1.0"
edition = "2018"
build = "build/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.27.0"

[build-dependencies]
gl_generator = "0.14.0"